/* ------ OTHERS ------ */
export const GET_ERRORS = 'GET_ERRORS'
export const REFRESH_ERRORS = 'REFRESH_ERRORS'
export const GET_LOADING = 'GET_LOADING'
export const GET_RESPONSE = 'GET_RESPONSE'
export const RESET_RESPONSE = 'RESET_RESPONSE'

/* ------ COMMON ------ */
export const SET_NAVBAR_VALUES = 'SET_NAVBAR_VALUES'

/* ------ AUTH ------ */
export const LOADING_AUTH = 'LOADING_AUTH'
export const STOP_LOADING_AUTH = 'STOP_LOADING_AUTH'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

/* ------ PROFILES ------ */
export const GET_PROFILE = 'GET_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const DELETE_PROFILE = 'DELETE_PROFILE'

/* ------ EXERCISES ------ */
export const GET_EXERCISE = 'GET_EXERCISE'
export const GET_EXERCISES = 'GET_EXERCISES'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'

/* ------ EXERCISE SETS ------ */
export const GET_EXERCISE_SET = 'GET_EXERCISE_SET'
export const GET_EXERCISE_SETS = 'GET_EXERCISE_SETS'
export const ADD_EXERCISE_SET = 'ADD_EXERCISE_SET'
export const UPDATE_EXERCISE_SET = 'UPDATE_EXERCISE_SET'
export const DELETE_EXERCISE_SET = 'DELETE_EXERCISE_SET'